[package]
name = "devp2p"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Wei Tang <hi@that.world>"]
description = "Ethereum's devp2p protocol implementation in Rust."
repository = "https://github.com/sorpaas/devp2p-rs"

[dependencies]
dpt = "0.2"
rlpx = "0.2"
futures = "0.1"
tokio-io = "0.1"
tokio-core = "0.1"
devp2p-secp256k1 = "0.5"
etcommon-bigint = "0.1"

[workspace]
members = [
  "./dpt",
  "./rlpx",
]