[package]
name = "rlpx"
version = "0.2.5"
license = "Apache-2.0"
authors = ["Wei Tang <hi@that.world>"]
description = "RLPx peer-to-peer protocol implementation in Rust."
repository = "https://github.com/sorpaas/devp2p-rs"

[dependencies]
mio = "0.6"
devp2p-secp256k1 = "0.5"
sha2 = "0.6"
sha3 = "0.6"
rand = "0.3.12"
byteorder = "1"
rust-crypto = "0.2"
etcommon-bigint = "0.1"
etcommon-crypto = "0.1"
etcommon-util = "0.1"
etcommon-rlp = "0.1"
bytes = "0.4"
futures = "0.1"
tokio-io = "0.1"
tokio-core = "0.1"
log = "0.3"

[dev-dependencies]
env_logger = "0.3"