[package]
name = "rlpx"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Wei Tang <hi@that.world>"]
description = "RLPx peer-to-peer protocol implementation in Rust."
repository = "https://github.com/sorpaas/devp2p-rs"

[dependencies]
mio = "0.6"
secp256k1 = "0.6"
rand = "0.3.12"
etcommon-bigint = "0.1"